version: "3.9"

services:

  postgres:
    container_name: pg-db
    image: postgres:14.5
    networks:
      - postgres
    environment:
      POSTGRES_DB: app_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/pginit:/docker-entrypoint-initdb.d
      - ./pg/pgdata:/var/lib/postgresql/data
      #- ./pg/postgresql.conf:/var/lib/postgresql/data/postgresql.conf # DevOps thing
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_storage"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4:6.13
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ag@ag.ru
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5051:443" # https
      - "5050:80"  # http
    volumes:
      - "./pg/pgadata:/var/lib/pgadmin"
    restart: unless-stopped

networks:

  postgres:
    driver: bridge