package errors

const (
	ERROR_NONE = 0

	ERROR_SYNTAX             = 400
	ERROR_FORBIDDEN          = 403
	ERROR_NOT_FOUND          = 404
	ERROR_METHOD_NOT_ALLOWED = 405
	ERROR_TIMEOUT            = 408

	ERROR_INTERNAL        = 500
	ERROR_NOT_IMPLEMENTED = 501
)
